version: "3.8"

services:
  kafka:
    image: bitnamilegacy/kafka:3.7.1
    container_name: kafka
    ports:
      - "9092:9092"     # host access
      - "29092:29092"   # docker access
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: broker,controller

      # listeners
      KAFKA_CFG_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092

      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      # KRaft controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093

      # inter-broker traffic must stay INTERNAL
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL

      ALLOW_PLAINTEXT_LISTENER: "yes"

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    environment:
      KAFKA_BROKERS: kafka:29092
    ports:
      - "8090:8080"
    depends_on:
      - kafka
